site_name: GenAI RAG Accelerator
repo_name: artefactory/skaff-rag-accelerator
repo_url: https://github.com/artefactory/skaff-rag-accelerator

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets

nav:
  - Home: index.md
  - The frontend: frontend.md
  - The database: database.md
