# This is only used for documentation generation in Roadie. It is not part of the vertex starter kit.

site_name: GenAI RAG Accelerator
repo_name: artefactory/skaff-rag-accelerator
repo_url: https://github.com/artefactory/skaff-rag-accelerator

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.snippets

nav:
  - Getting started: getting_started.md
  - The frontend: frontend.md
  - The backend:
    - The backend: backend/backend.md
    - RAG and RAGConfig classes: backend/rag_ragconfig.md
    - Plugins:
      - Plugins: backend/plugins/plugins.md
      - Memory and sessions: backend/plugins/conversational_rag_plugin
      - Authentication: backend/plugins/authentication.md
      - Secure user-based sessions: backend/plugins/user_based_sessions.md
  - The database: database.md
  - Deployment:
    - Admin Mode: deployment/admin_mode.md
  - Cookbook:
    - config.yaml recipes:
      - LLMs: cookbook/configs/llms_configs.md
      - Vector Stores: cookbook/configs/vector_stores_configs.md
      - Embedding Models: cookbook/configs/embedding_models_configs.md
      - Databases: cookbook/configs/databases_configs.md
    - How to load documents in the RAG: cookbook/loading_documents.md
    - How to extend the RAGConfig: cookbook/extend_ragconfig.md
