LLMConfig: &LLMConfig
  source: AzureChatOpenAI
  source_config:
    openai_api_type: azure
    openai_api_key: {{ OPENAI_API_KEY }}
    openai_api_base: https://genai-ds.openai.azure.com/
    openai_api_version: 2023-07-01-preview
    deployment_name: gpt4
  temperature: 0.1

VectorStoreConfig: &VectorStoreConfig
  source: Chroma
  source_config:
    persist_directory: vector_database/
    collection_metadata:
      hnsw:space: cosine

  retriever_search_type: similarity_score_threshold
  retriever_config:
    k: 20
    score_threshold: 0.5

  insertion_mode: null

EmbeddingModelConfig: &EmbeddingModelConfig
  source: OpenAIEmbeddings
  source_config:
    openai_api_type: azure
    openai_api_key: {{ EMBEDDING_API_KEY }}
    openai_api_base: https://poc-openai-artefact.openai.azure.com/
    deployment: embeddings
    chunk_size: 500

DatabaseConfig: &DatabaseConfig
  database_url: {{ DATABASE_URL }}

RagConfig:
  llm: *LLMConfig
  vector_store: *VectorStoreConfig
  embedding_model: *EmbeddingModelConfig
  database: *DatabaseConfig
  chat_history_window_size: 5
  max_tokens_limit: 3000
  response_mode: stream
