LLMConfig: &LLMConfig
  source: ChatVertexAI
  source_config:
    project_id: genai-vertex
    model_name: chat-bison@001
    location: europe-west1
    max_output_tokens: 512
  temperature: 0.1

VectorStoreConfig: &VectorStoreConfig
  source: MatchingEngine
  source_config:
    project_id: genai-vertex
    gcs_bucket_name: rag_accelerator_matchin_engine
    persist_directory: vector_database/
    collection_metadata:
      hnsw:space: cosine

  retriever_search_type: similarity
  retriever_config:
    k: 10

  insertion_mode: null

EmbeddingModelConfig: &EmbeddingModelConfig
  source: VertexAIEmbeddings
  source_config:
    location: europe-west1
    project_id: genai-vertex
    model_name: textembedding-gecko@001


DatabaseConfig: &DatabaseConfig
  database_url: {{ DATABASE_URL }}

RagConfig:
  llm: *LLMConfig
  vector_store: *VectorStoreConfig
  embedding_model: *EmbeddingModelConfig
  database: *DatabaseConfig
  chat_history_window_size: 5
  max_tokens_limit: 3000
  response_mode: stream
