llm_provider_config:
  openai_api_type: azure
  openai_api_base: https://poc-genai-gpt4.openai.azure.com/
  openai_api_version: 2023-07-01-preview
  openai_api_key: {{ OPENAI_API_KEY }}

llm_model_config:
  model_source: AzureChatOpenAI
  deployment_name: gpt4v
  temperature: 0.1

embedding_provider_config:
  openai_api_type: azure
  openai_api_base: https://poc-openai-artefact.openai.azure.com/
  openai_api_key: {{ EMBEDDING_API_KEY }}

embedding_model_config:
  model_source: OpenAIEmbeddings
  deployment: embeddings
  chunk_size: 500

vector_store_provider:
  model_source: Chroma
  persist_directory: vector_database/
  documents_to_retreive: 10
  collection_metadata:
    hnsw:space: cosine
  search_type: similarity
  search_options:
    score_threshold: 0.5
    top_k: 20

chat_message_history_config:
  source: ChatMessageHistory
  window_size: 5
