LLMConfig: &LLMConfig
  source: AzureChatOpenAI
  source_config:
    openai_api_type: azure
    azure_endpoint: https://cursor-france-ds.openai.azure.com/
    deployment_name: gpt-4o
    api_version: 2025-01-01-preview
    temperature: 0.1

VectorStoreConfig: &VectorStoreConfig
  source: Chroma
  source_config:
    persist_directory: vector_database/
    collection_metadata:
      hnsw:space: cosine

  insertion_mode: null

EmbeddingModelConfig: &EmbeddingModelConfig
  source: HuggingFaceEmbeddings
  source_config:
    model_name: BAAI/bge-base-en-v1.5
    encode_kwargs: {chunk_size: 500}

DatabaseConfig: &DatabaseConfig
  database_url: sqlite://Ò/database/rag.sqlite3

RagConfig:
  llm: *LLMConfig
  vector_store: *VectorStoreConfig
  embedding_model: *EmbeddingModelConfig
  database: *DatabaseConfig
  chat_history_window_size: 5
  max_tokens_limit: 3000
  response_mode: stream
