llm_provider_config:
  openai_api_type: azure
  openai_api_base: https://poc-genai-gpt4.openai.azure.com/
  openai_api_version: 2023-07-01-preview
  openai_api_key: {{ OPENAI_API_KEY }}

llm_model_config:
  model_source: AzureChatOpenAI
  deployment_name: gpt4v
  temperature: 0.1
  streaming: true
  verbose: true

embedding_provider_config:
  openai_api_base: https://poc-openai-artefact.openai.azure.com/
  openai_api_key: {{ EMBEDDING_API_KEY }}
  openai_api_type: azure

embedding_model_config:
  model_source: OpenAIEmbeddings
  deployment: embeddings
  chunk_size: 16

vector_store_provider:
  model_source: Chroma
  persist_directory: database/
