llm_provider_config:
  openai_api_type: azure
  openai_api_base: https://poc-genai-gpt4.openai.azure.com/
  openai_api_version: 2023-07-01-preview
  openai_api_key: 

llm_model_config:
  model_source: AzureChatOpenAI
  deployment_name: gpt4v
  temperature: 0.1
  streaming: true
  verbose: true

embedding_provider_config:
  openai_api_base: "https://poc-openai-artefact.openai.azure.com/"
  openai_api_key: 

embedding_model_config:
  model_source: OpenAIEmbeddings
  deployment: text-embedding-ada-002
  chunk_size: 16